### ISSUE TITLE
POST request is not working

### ISSUE THREAD

**Issue by pjain287074** [albanoj2/order-rest-backend#4]
Hi 
 I am New to JAVA  and I was trying to use run your code.. its up and running. I am able to view  empty order on link http://localhost:8080/order.
But could you please help me with the format of POST request since its not documented that what params need to send while making POST request. i am getting below error while trying to POST a order

{"timestamp":1613580901577,"status":400,"error":"Bad Request","exception":"org.springframework.http.converter.HttpMessageNotReadableException","message":"Required request body is missing: public org.springframework.http.ResponseEntity com.dzone.albanoj2.example.rest.controller.OrderController.createOrder(com.dzone.albanoj2.example.rest.domain.Order)","path":"/order"}

I am sure there must be some specific format of POST request .. I am using below POST request
http://localhost:8080/order?message=firstorder

**Comment by jmdopereiro** [comment]
Are you adding the payload in the request body ?

**Comment by pjain287074** [comment]
Can you please help me with the payload sample

**Comment by jmdopereiro** [comment]
what are you using to make the request ? postman ?

**Comment by pjain287074** [comment]
Yes I am using postman.

**Comment by pjain287074** [comment]
You can suggest any other methods as well.
For me it's not necessary to use postman.. I can use Curl command as well.
Please let me know payload which need to send while making request.


Thanks in advance

**Comment by jmdopereiro** [comment]
This payload worked for me
`{"id":1,"description":"my order","contInCents":30,"isComplete":true}`

**Comment by jmdopereiro** [comment]
Also had to set the header
`Content-Type: application/json`

**Comment by pjain287074** [comment]
Thank you for your response.. I will try this and let you know in case I
face any problem.

>

**Comment by pjain287074** [comment]
Issue fixed
